[package]
name = "rs-sharding"
version = "0.1.0"
authors = ["Arthur De Witte <arthur.dewitte@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8.6"
